### ISSUE TITLE
Windows 11 compatibility / Attempts 2+ don't work

### ISSUE THREAD

**Issue by nikitamendelbaum** [ldstein/terminate-icue#1]
Not sure if the problem is with Win11 or something else - the setup script ran fine (options 1 and 3), but on reboot iCue still runs as usual. I guess the task is not being added to Win Task Scheduler

**Comment by ldstein** [comment]
Thanks for the heads up. I haven't actually tested it on Windows 11 yet - I'll add that to my todo list.

To confirm, iCue is autostarting after login but does not automatically terminate ~10-20 seconds later?

**Comment by nikitamendelbaum** [comment]
Correct. As I said, the setup script ran fine for options 1 and 3. Then I reboot and the iCue is auto-started, my default animated icue profile is enabled and then iCue never gets forced to quit. I can open it and change the profiles in sys tray with right click.
However, if I bring the iCue to the foreground, there is an error in the top right corner of the app saying that it failed to start iCue service. But all the keyboard rgb settings are still working.

Using that chance, I just want to thank you for making an effort to fix the problem. It's such a shame that Lenovo was able to engineer such a great laptop - thin, powerful and yet quiet and cool, and just screwed up on the minor things which still matter.  I also find it ridiculous that the keyboard RGB brightness levels are limited to "blind-typing", "super bright", "hurt your eyes" and "that's why we ship that laptop with 300watt adapter!".

**Comment by ldstein** [comment]
> However, if I bring the iCue to the foreground, there is an error in the top right corner of the app saying that it failed to start iCue service. But all the keyboard rgb settings are still working.

That is normal, you can safely ignore the warning.

>  I also find it ridiculous that the keyboard RGB brightness levels are limited to "blind-typing", "super bright", "hurt your eyes"...

Completely agree with you regarding the built-in presets. Thankfully that can be adjusted with a custom profile in iCue by using less bright colors. 

Could you try this:

- Ensure iCue is running
- Launch Task Scheduler (`Start > Windows Administrative Tools > Task Scheduler`)
- Locate the Task "Terminate iCue", right-click and choose "Run" (See image below)
- Observe if iCue gets terminated

If any of that fails, try double clicking `terminate-icue.bat`. This should kill the iCue process. That would help identify if the issue is the script itself or the scheduled task.

![image](https://user-images.githubusercontent.com/3657344/153348011-cb1dfbfe-8b3c-43a3-93ec-fa1372c1ae1b.png)

**Comment by nikitamendelbaum** [comment]
Manually running the task from the Task Scheduler worked - the iCue was force-closed after ~7-10 seconds after I ran the task. But then I restart and the iCue is autostarted ~10 seconds after I signed in to Windows and remains running. 
I am not sure if it is me doing something wrong or is it some difference in the way Win11 handles the tasks on logon

**Comment by nikitamendelbaum** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/5171767/153691454-dc6b5375-9e88-4e3f-a910-9ff423fa227e.png">
<img width="391" alt="image" src="https://user-images.githubusercontent.com/5171767/153691493-8cc50444-80f3-4929-84e7-5d1398ed204d.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/5171767/153691507-38d132a2-d82b-4943-ac73-2845b8c8ffe0.png">

**Comment by ldstein** [comment]
Thanks. Those settings all look OK.

I tested Terminate iCue and iCue on a Windows 11 Virtual Machine. All seems to be working on my end.

Could you try the following:

1. Ensure iCue is running
2. Launch Task Scheduler (`Start > Windows Administrative Tools > Task Scheduler`)
3. Right-click the "Terminate iCue" task and click  `Run` [1] (See image below)
5. Wait 30 seconds.
6. In Task Scheduler, press F5 (refreshes all the columns)
5. Report if the "last run time" [2] changes and the "last run result" [3]
6. Confirm if iCue gets terminated when running the task manually

![image](https://user-images.githubusercontent.com/3657344/153695388-fce0633a-82e7-44b7-924a-2ee50378f6f3.png)

**Comment by nikitamendelbaum** [comment]
I followed the steps and the Last Run Time was updated as expected along with Last Run Result 0x0, and the iCue quit when running the task manually . 
However, what I noticed is that the auto-started run always has Last Run Result 0x1 and it does not kill iCue.

**Comment by nikitamendelbaum** [comment]
May be this may give some clue:
```
tasklist /fi "ImageName eq icue.exe" /fo csv 2>NUL
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:',
call CreateFile, then use the FileStream constructors that take an OS handle as an IntPtr.
At line:1 char:1
+ tasklist /fi "ImageName eq icue.exe" /fo csv 2>NUL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by nikitamendelbaum** [comment]
Here is what 's happening on the login, I think...
```
C:\_utils\terminate-icue-main>terminate-icue.bat --cycle
Attempt #0/12 - iCue not running, checking again in 5 seconds

Waiting for 0 seconds, press a key to continue ...
The system cannot find the batch label specified - Check_iCue_Running
```
Goto does not work for attempt 2. Looks like goto in batch only works for functions declared after the goto is called.

My temporary solution is ugly but working - I added 12 of the :Check_iCue_Running[2..13] functions that call each other 1 by 1. That helped with "goto :self" and fixed my problem on the restart.

So, that also makes me think that somehow the iCue.exe on your machine is starting quicker than on mine (it takes about 15 seconds on my machine after login for iCue to start and change the keyboard RGB) and your script is able to kill it on the first attempt (in the first 5 seconds). I am curios why is mine taking longer to start.

But the 2+ attempt's goto needs to be fixed in the script.

**Comment by ldstein** [comment]
Ah! Think I worked it out. 

The error you mentioned above occurs when the line breaks are converted from Windows style (CR/LF) to Unix style (LF).

This would happen if you download the repo via the "Download ZIP" button (Git usually normalises the line breaks when you commit changes).

![image](https://user-images.githubusercontent.com/3657344/153756480-27a59f6d-7656-4779-8599-343fd465d4b0.png)

Try using the release from https://github.com/ldstein/terminate-icue/releases/tag/v1.0.0 and see if that works.

I learned something new today. Will look at disabling the line feed conversion in the repo to prevent this from happening.

**Comment by nikitamendelbaum** [comment]
Oh, interesting! Works now! Thank you!
Thought it is the problem of using goto with the function declared earlier in the batch script, but turned out to be the CRLF issue. I am a Linux dev, not very familiar with all that Windows stuff.
Closing now.
P.S. Again, thank you for this script!

**Comment by ldstein** [comment]
No worries, I didn't know about the CRLF / goto interpretation either. Glad we found the root of the problem.
