### ISSUE TITLE
Delay Before Process Termination

### ISSUE THREAD

**Issue by ACiDxCHRiST** [ldstein/terminate-icue#2]
2021 AMD Legion 7

I am having an issue with Terminate iCue closing iCue before it has applied my user configured lighting profile. Basically the chain of events are:

1) Laptop Off
2) AC Adapter Disconnected
3) AC Adapter Connected
4) Turn on Laptop
5) Disco Lights Commence
6) Sign-in to Windows ASAP
7) iCue process starts
8) Terminate iCue detects it and terminates it

The problem seems to be that in between Step 7 and 8, iCue doesn't apply my static lighting profile before it gets terminated and so I am left with DISCO DISCO! indefinitely. At this point I am stuck with Terminate iCue not being helpful because even if I don't disconnect the AC adapter moving forward, no matter how many times I reboot, iCue is never able to apply the static lighting profile before it gets killed.

I think there needs to be a delay added between when Terminate iCue detects iCue and when it actually terminates it or the plugin host process. Or if there is a delay, it needs to be lengthened for reliability because it is certainly not reliable on my system.

**Comment by ACiDxCHRiST** [comment]
I should have first actually looked at the script and seen I can easily modify the required functionality and then reported my feedback rather than opening the issue first.

I changed $minRunningTime to 40 and now I will use it for a while to see if fails anymore.

**Comment by ACiDxCHRiST** [comment]
I am still having some reboots where iCue takes a really long time before it applies my user configured profile on boot; but with $minRunningTime set to 40, I haven't seen it fail to apply the profile before being terminated yet.

**Comment by ldstein** [comment]
Hi, sorry for the delayed response.

Glad you have it resolved and thanks for advising how you resolved the issue.

I'll adjust the minRunningTime to 40 on the next release of Terminate iCue.
